-- =====================================================================
-- Modelado y Gestión de una Base de Datos Hospitalaria
-- DDL: definición de la base de datos "hospitales_occidente"
-- SGBD: PostgreSQL 16+
--
-- Uso:
--   psql -U postgres -c "CREATE DATABASE hospitales_occidente ENCODING 'UTF8';"
--   psql -U postgres -d hospitales_occidente -f 01_ddl.sql
--
-- Convenciones de nombres:
--   pk_<tabla>, fk_<tabla>_<referencia>, uq_<tabla>_<campos>, ck_<tabla>_<regla>
-- La justificación de cada acción referencial está en el diccionario de datos (PDF).
-- =====================================================================

DROP SCHEMA IF EXISTS hospital CASCADE;
CREATE SCHEMA hospital;
SET search_path TO hospital;

-- =====================================================================
-- 1. UBICACIÓN GEOGRÁFICA
-- =====================================================================

-- Departamentos de Guatemala (catálogo)
CREATE TABLE departamento (
    id_departamento  SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_departamento PRIMARY KEY (id_departamento),
    CONSTRAINT uq_departamento_nombre UNIQUE (nombre)
);

-- Municipios de cada departamento (catálogo)
CREATE TABLE municipio (
    id_municipio     INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_departamento  SMALLINT     NOT NULL,
    nombre           VARCHAR(60)  NOT NULL,
    CONSTRAINT pk_municipio PRIMARY KEY (id_municipio),
    CONSTRAINT uq_municipio_depto_nombre UNIQUE (id_departamento, nombre),
    CONSTRAINT fk_municipio_departamento FOREIGN KEY (id_departamento)
        REFERENCES departamento (id_departamento)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =====================================================================
-- 2. PERSONAS (supertipo) Y SUBTIPOS
-- =====================================================================

-- Datos comunes de toda persona: pacientes, encargados, médicos y enfermeros
CREATE TABLE persona (
    id_persona        INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    nombres           VARCHAR(80)   NOT NULL,
    apellidos         VARCHAR(80)   NOT NULL,
    dpi               CHAR(13),
    fecha_nacimiento  DATE          NOT NULL,
    sexo              VARCHAR(9)    NOT NULL,
    estado_civil      VARCHAR(12),
    telefono          VARCHAR(8),
    direccion         VARCHAR(150),
    id_municipio      INTEGER       NOT NULL,
    area              VARCHAR(6)    NOT NULL,
    CONSTRAINT pk_persona PRIMARY KEY (id_persona),
    CONSTRAINT uq_persona_dpi UNIQUE (dpi),
    -- DPI: exactamente 13 dígitos numéricos
    CONSTRAINT ck_persona_dpi CHECK (dpi ~ '^[0-9]{13}$'),
    -- Sexo limitado a Masculino / Femenino
    CONSTRAINT ck_persona_sexo CHECK (sexo IN ('Masculino', 'Femenino')),
    -- Estado civil con valores válidos
    CONSTRAINT ck_persona_estado_civil CHECK (estado_civil IN ('Soltero', 'Casado', 'Unido', 'Divorciado', 'Viudo')),
    -- Teléfono guatemalteco de 8 dígitos
    CONSTRAINT ck_persona_telefono CHECK (telefono ~ '^[0-9]{8}$'),
    -- Área de residencia Urbana / Rural
    CONSTRAINT ck_persona_area CHECK (area IN ('Urbana', 'Rural')),
    -- Fecha de nacimiento dentro de un rango razonable
    CONSTRAINT ck_persona_fecha_nac CHECK (fecha_nacimiento >= DATE '1900-01-01'),
    CONSTRAINT fk_persona_municipio FOREIGN KEY (id_municipio)
        REFERENCES municipio (id_municipio)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Subtipo de persona: paciente atendido en algún hospital de la cadena
CREATE TABLE paciente (
    id_paciente        INTEGER      NOT NULL,
    no_expediente      VARCHAR(20)  NOT NULL,
    no_seguro_social   VARCHAR(20),
    fecha_registro     DATE         NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT pk_paciente PRIMARY KEY (id_paciente),
    CONSTRAINT uq_paciente_expediente UNIQUE (no_expediente),
    CONSTRAINT uq_paciente_seguro UNIQUE (no_seguro_social),
    CONSTRAINT fk_paciente_persona FOREIGN KEY (id_paciente)
        REFERENCES persona (id_persona)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Asociativa paciente-encargado (M:N): responsables de cada paciente
CREATE TABLE paciente_encargado (
    id_paciente   INTEGER      NOT NULL,
    id_encargado  INTEGER      NOT NULL,
    parentesco    VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_paciente_encargado PRIMARY KEY (id_paciente, id_encargado),
    -- Parentesco con valores válidos
    CONSTRAINT ck_paciente_encargado_parentesco CHECK (parentesco IN
        ('Padre', 'Madre', 'Hijo', 'Hija', 'Cónyuge', 'Hermano', 'Hermana',
         'Abuelo', 'Abuela', 'Tío', 'Tía', 'Tutor legal', 'Otro')),
    -- Un paciente no puede ser su propio encargado
    CONSTRAINT ck_paciente_encargado_distinto CHECK (id_paciente <> id_encargado),
    CONSTRAINT fk_paciente_encargado_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_paciente_encargado_persona FOREIGN KEY (id_encargado)
        REFERENCES persona (id_persona)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Catálogo de especialidades médicas
CREATE TABLE especialidad (
    id_especialidad  SMALLINT     GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(60)  NOT NULL,
    CONSTRAINT pk_especialidad PRIMARY KEY (id_especialidad),
    CONSTRAINT uq_especialidad_nombre UNIQUE (nombre)
);

-- Subtipo de persona: médico (residente, interno, externo o practicante)
CREATE TABLE medico (
    id_medico           INTEGER        NOT NULL,
    no_colegiado        VARCHAR(10),
    tipo_medico         VARCHAR(11)    NOT NULL,
    institucion_origen  VARCHAR(100),
    costo_consulta      NUMERIC(10,2),
    CONSTRAINT pk_medico PRIMARY KEY (id_medico),
    CONSTRAINT uq_medico_colegiado UNIQUE (no_colegiado),
    -- Tipo de médico según su vínculo con el hospital
    CONSTRAINT ck_medico_tipo CHECK (tipo_medico IN ('Residente', 'Interno', 'Externo', 'Practicante')),
    -- Solo el practicante puede no tener número de colegiado
    CONSTRAINT ck_medico_colegiado CHECK (tipo_medico = 'Practicante' OR no_colegiado IS NOT NULL),
    -- La institución de origen es obligatoria solo para médicos externos
    CONSTRAINT ck_medico_externo CHECK ((tipo_medico = 'Externo') = (institucion_origen IS NOT NULL)),
    -- El costo de consulta debe ser positivo
    CONSTRAINT ck_medico_costo CHECK (costo_consulta > 0),
    CONSTRAINT fk_medico_persona FOREIGN KEY (id_medico)
        REFERENCES persona (id_persona)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Asociativa médico-especialidad (M:N)
CREATE TABLE medico_especialidad (
    id_medico        INTEGER   NOT NULL,
    id_especialidad  SMALLINT  NOT NULL,
    CONSTRAINT pk_medico_especialidad PRIMARY KEY (id_medico, id_especialidad),
    CONSTRAINT fk_medico_especialidad_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_medico)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_medico_especialidad_especialidad FOREIGN KEY (id_especialidad)
        REFERENCES especialidad (id_especialidad)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Subtipo de persona: enfermero registrado o practicante de enfermería
CREATE TABLE enfermero (
    id_enfermero    INTEGER      NOT NULL,
    no_registro     VARCHAR(10),
    tipo_enfermero  VARCHAR(11)  NOT NULL,
    CONSTRAINT pk_enfermero PRIMARY KEY (id_enfermero),
    CONSTRAINT uq_enfermero_registro UNIQUE (no_registro),
    -- Tipo de enfermero Registrado / Practicante
    CONSTRAINT ck_enfermero_tipo CHECK (tipo_enfermero IN ('Registrado', 'Practicante')),
    -- El enfermero registrado debe tener número de registro
    CONSTRAINT ck_enfermero_registro CHECK (tipo_enfermero = 'Practicante' OR no_registro IS NOT NULL),
    CONSTRAINT fk_enfermero_persona FOREIGN KEY (id_enfermero)
        REFERENCES persona (id_persona)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- =====================================================================
-- 3. HOSPITALES, UNIDADES, SERVICIOS Y RECURSOS FÍSICOS
-- =====================================================================

-- Hospitales de la cadena y establecimientos externos (para traslados/referencias)
CREATE TABLE hospital (
    id_hospital            SMALLINT      GENERATED BY DEFAULT AS IDENTITY,
    nombre                 VARCHAR(100)  NOT NULL,
    descripcion            VARCHAR(250),
    direccion              VARCHAR(150)  NOT NULL,
    id_municipio           INTEGER       NOT NULL,
    telefono               VARCHAR(8),
    pertenece_institucion  BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_hospital PRIMARY KEY (id_hospital),
    CONSTRAINT uq_hospital_nombre UNIQUE (nombre),
    -- Teléfono de 8 dígitos
    CONSTRAINT ck_hospital_telefono CHECK (telefono ~ '^[0-9]{8}$'),
    CONSTRAINT fk_hospital_municipio FOREIGN KEY (id_municipio)
        REFERENCES municipio (id_municipio)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Unidades médicas de cada hospital (Consulta externa, Emergencias, Cirugía, Hospitalización, Otro)
CREATE TABLE unidad_medica (
    id_unidad      INTEGER        GENERATED BY DEFAULT AS IDENTITY,
    id_hospital    SMALLINT       NOT NULL,
    tipo_unidad    VARCHAR(17)    NOT NULL,
    telefono       VARCHAR(8),
    costo_dia      NUMERIC(10,2),
    CONSTRAINT pk_unidad_medica PRIMARY KEY (id_unidad),
    CONSTRAINT uq_unidad_medica_hosp_tipo UNIQUE (id_hospital, tipo_unidad),
    -- Tipo de unidad médica válido
    CONSTRAINT ck_unidad_medica_tipo CHECK (tipo_unidad IN
        ('Consulta externa', 'Emergencias', 'Cirugía', 'Hospitalización', 'Otro')),
    -- Teléfono de 8 dígitos
    CONSTRAINT ck_unidad_medica_telefono CHECK (telefono ~ '^[0-9]{8}$'),
    -- Costo por día solo aplica (y es no negativo) en Hospitalización
    CONSTRAINT ck_unidad_medica_costo_dia CHECK (costo_dia IS NULL OR (tipo_unidad = 'Hospitalización' AND costo_dia >= 0)),
    CONSTRAINT fk_unidad_medica_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Catálogo de servicios / tipos de atención médica, clasificados por tipo de unidad
CREATE TABLE servicio (
    id_servicio  SMALLINT      GENERATED BY DEFAULT AS IDENTITY,
    nombre       VARCHAR(80)   NOT NULL,
    tipo_unidad  VARCHAR(17)   NOT NULL,
    CONSTRAINT pk_servicio PRIMARY KEY (id_servicio),
    CONSTRAINT uq_servicio_nombre_tipo UNIQUE (nombre, tipo_unidad),
    -- Tipo de unidad a la que pertenece el servicio
    CONSTRAINT ck_servicio_tipo_unidad CHECK (tipo_unidad IN
        ('Consulta externa', 'Emergencias', 'Cirugía', 'Hospitalización', 'Otro'))
);

-- Asociativa unidad-servicio (M:N): servicios ofrecidos por cada unidad y su costo
CREATE TABLE unidad_servicio (
    id_unidad    INTEGER        NOT NULL,
    id_servicio  SMALLINT       NOT NULL,
    costo        NUMERIC(10,2)  NOT NULL,
    CONSTRAINT pk_unidad_servicio PRIMARY KEY (id_unidad, id_servicio),
    -- El costo del servicio no puede ser negativo
    CONSTRAINT ck_unidad_servicio_costo CHECK (costo >= 0),
    CONSTRAINT fk_unidad_servicio_unidad FOREIGN KEY (id_unidad)
        REFERENCES unidad_medica (id_unidad)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_unidad_servicio_servicio FOREIGN KEY (id_servicio)
        REFERENCES servicio (id_servicio)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Asociativa médico-unidad (M:N): asignación laboral de médicos a unidades
CREATE TABLE medico_unidad (
    id_medico     INTEGER      NOT NULL,
    id_unidad     INTEGER      NOT NULL,
    fecha_inicio  DATE         NOT NULL,
    jornada       VARCHAR(11)  NOT NULL,
    es_jefe       BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_medico_unidad PRIMARY KEY (id_medico, id_unidad),
    -- Jornada laboral válida
    CONSTRAINT ck_medico_unidad_jornada CHECK (jornada IN
        ('Matutina', 'Vespertina', 'Mixta', 'Por turnos', 'Por llamado')),
    CONSTRAINT fk_medico_unidad_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_medico)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_medico_unidad_unidad FOREIGN KEY (id_unidad)
        REFERENCES unidad_medica (id_unidad)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Asociativa enfermero-unidad (M:N): asignación laboral de enfermeros a unidades
CREATE TABLE enfermero_unidad (
    id_enfermero  INTEGER      NOT NULL,
    id_unidad     INTEGER      NOT NULL,
    fecha_inicio  DATE         NOT NULL,
    jornada       VARCHAR(11)  NOT NULL,
    es_jefe       BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_enfermero_unidad PRIMARY KEY (id_enfermero, id_unidad),
    -- Jornada laboral válida
    CONSTRAINT ck_enfermero_unidad_jornada CHECK (jornada IN
        ('Matutina', 'Vespertina', 'Mixta', 'Por turnos', 'Por llamado')),
    CONSTRAINT fk_enfermero_unidad_enfermero FOREIGN KEY (id_enfermero)
        REFERENCES enfermero (id_enfermero)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_enfermero_unidad_unidad FOREIGN KEY (id_unidad)
        REFERENCES unidad_medica (id_unidad)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Turnos de 12 horas de la unidad de Emergencias
CREATE TABLE turno_emergencia (
    id_turno   INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    id_unidad  INTEGER     NOT NULL,
    fecha      DATE        NOT NULL,
    jornada    VARCHAR(8)  NOT NULL,
    CONSTRAINT pk_turno_emergencia PRIMARY KEY (id_turno),
    CONSTRAINT uq_turno_emergencia UNIQUE (id_unidad, fecha, jornada),
    -- Turnos de 12 h: Diurno (07:00-19:00) o Nocturno (19:00-07:00)
    CONSTRAINT ck_turno_emergencia_jornada CHECK (jornada IN ('Diurno', 'Nocturno')),
    CONSTRAINT fk_turno_emergencia_unidad FOREIGN KEY (id_unidad)
        REFERENCES unidad_medica (id_unidad)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Asociativa turno-médico (M:N): médicos que cubren cada turno de emergencia
CREATE TABLE turno_medico (
    id_turno   INTEGER  NOT NULL,
    id_medico  INTEGER  NOT NULL,
    CONSTRAINT pk_turno_medico PRIMARY KEY (id_turno, id_medico),
    CONSTRAINT fk_turno_medico_turno FOREIGN KEY (id_turno)
        REFERENCES turno_emergencia (id_turno)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_turno_medico_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Clínicas / consultorios de la Consulta externa
CREATE TABLE clinica (
    id_clinica  INTEGER   GENERATED BY DEFAULT AS IDENTITY,
    id_unidad   INTEGER   NOT NULL,
    numero      SMALLINT  NOT NULL,
    CONSTRAINT pk_clinica PRIMARY KEY (id_clinica),
    CONSTRAINT uq_clinica_unidad_numero UNIQUE (id_unidad, numero),
    -- Número de clínica positivo
    CONSTRAINT ck_clinica_numero CHECK (numero > 0),
    CONSTRAINT fk_clinica_unidad FOREIGN KEY (id_unidad)
        REFERENCES unidad_medica (id_unidad)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Camillas de Emergencias y Hospitalización
CREATE TABLE camilla (
    id_camilla  INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_unidad   INTEGER      NOT NULL,
    codigo      VARCHAR(10)  NOT NULL,
    estado      VARCHAR(13)  NOT NULL DEFAULT 'Disponible',
    CONSTRAINT pk_camilla PRIMARY KEY (id_camilla),
    CONSTRAINT uq_camilla_unidad_codigo UNIQUE (id_unidad, codigo),
    -- Estado operativo de la camilla
    CONSTRAINT ck_camilla_estado CHECK (estado IN ('Disponible', 'Ocupada', 'Mantenimiento', 'Inactiva')),
    CONSTRAINT fk_camilla_unidad FOREIGN KEY (id_unidad)
        REFERENCES unidad_medica (id_unidad)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Quirófanos (pabellones) de la unidad de Cirugía: 4 por hospital
CREATE TABLE quirofano (
    id_quirofano  INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_unidad     INTEGER      NOT NULL,
    numero        SMALLINT     NOT NULL,
    estado        VARCHAR(13)  NOT NULL DEFAULT 'Disponible',
    CONSTRAINT pk_quirofano PRIMARY KEY (id_quirofano),
    CONSTRAINT uq_quirofano_unidad_numero UNIQUE (id_unidad, numero),
    -- Cada unidad de Cirugía tiene cuatro quirófanos (1 a 4)
    CONSTRAINT ck_quirofano_numero CHECK (numero BETWEEN 1 AND 4),
    -- Estado operativo del quirófano
    CONSTRAINT ck_quirofano_estado CHECK (estado IN ('Disponible', 'Ocupado', 'Mantenimiento', 'Inactivo')),
    CONSTRAINT fk_quirofano_unidad FOREIGN KEY (id_unidad)
        REFERENCES unidad_medica (id_unidad)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- =====================================================================
-- 4. CONSULTA EXTERNA
-- =====================================================================

-- Catálogo de medicamentos
CREATE TABLE medicamento (
    id_medicamento  INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(80)  NOT NULL,
    presentacion    VARCHAR(60)  NOT NULL,
    CONSTRAINT pk_medicamento PRIMARY KEY (id_medicamento),
    CONSTRAINT uq_medicamento_nombre_pres UNIQUE (nombre, presentacion)
);

-- Ficha de cita programada de Consulta externa (con control de estado y costo)
CREATE TABLE cita (
    id_cita                  INTEGER        GENERATED BY DEFAULT AS IDENTITY,
    id_paciente              INTEGER        NOT NULL,
    id_medico                INTEGER        NOT NULL,
    id_clinica               INTEGER        NOT NULL,
    fecha_hora               TIMESTAMP      NOT NULL,
    medio_solicitud          VARCHAR(20)    NOT NULL,
    tipo_cita                VARCHAR(16)    NOT NULL,
    es_referido              BOOLEAN        NOT NULL DEFAULT FALSE,
    id_hospital_referente    SMALLINT,
    estado                   VARCHAR(12)    NOT NULL DEFAULT 'Programada',
    cancelacion_notificada   BOOLEAN,
    id_cita_anterior         INTEGER,
    costo_base               NUMERIC(10,2)  NOT NULL,
    porcentaje_costo         NUMERIC(5,2)   NOT NULL,
    recargo_cancelacion      BOOLEAN        NOT NULL DEFAULT FALSE,
    costo_total              NUMERIC(10,2)  GENERATED ALWAYS AS (
        ROUND(costo_base * porcentaje_costo / 100
              * CASE WHEN recargo_cancelacion THEN 1.10 ELSE 1 END, 2)) STORED,
    CONSTRAINT pk_cita PRIMARY KEY (id_cita),
    -- Medio por el que se solicitó la cita
    CONSTRAINT ck_cita_medio CHECK (medio_solicitud IN ('Teléfono', 'Correo', 'Recepción general')),
    -- Primera consulta o reconsulta
    CONSTRAINT ck_cita_tipo CHECK (tipo_cita IN ('Primera consulta', 'Reconsulta')),
    -- Estado de la cita
    CONSTRAINT ck_cita_estado CHECK (estado IN ('Programada', 'Realizada', 'Reprogramada', 'Cancelada')),
    -- Consulta externa solo en turno matutino (06:00 a 12:59)
    CONSTRAINT ck_cita_horario CHECK (fecha_hora::TIME BETWEEN TIME '06:00' AND TIME '12:59'),
    -- Si es referido debe indicarse la institución que refiere, y viceversa
    CONSTRAINT ck_cita_referido CHECK (es_referido = (id_hospital_referente IS NOT NULL)),
    -- Solo las citas canceladas indican si la cancelación fue notificada
    CONSTRAINT ck_cita_cancelacion CHECK ((estado = 'Cancelada') = (cancelacion_notificada IS NOT NULL)),
    -- Costo base positivo
    CONSTRAINT ck_cita_costo_base CHECK (costo_base > 0),
    -- Porcentaje: 80% referido, 75% reconsulta, 100% primera consulta
    CONSTRAINT ck_cita_porcentaje CHECK (porcentaje_costo =
        CASE WHEN es_referido THEN 80 WHEN tipo_cita = 'Reconsulta' THEN 75 ELSE 100 END),
    -- Una cita no puede referenciarse a sí misma
    CONSTRAINT ck_cita_anterior CHECK (id_cita_anterior <> id_cita),
    CONSTRAINT fk_cita_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cita_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cita_clinica FOREIGN KEY (id_clinica)
        REFERENCES clinica (id_clinica)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cita_hospital_referente FOREIGN KEY (id_hospital_referente)
        REFERENCES hospital (id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cita_cita_anterior FOREIGN KEY (id_cita_anterior)
        REFERENCES cita (id_cita)
        ON DELETE SET NULL ON UPDATE CASCADE
);

-- Ficha de consulta del paciente: registro de la consulta realizada (1:1 con cita)
CREATE TABLE consulta (
    id_consulta    INTEGER    GENERATED BY DEFAULT AS IDENTITY,
    id_cita        INTEGER    NOT NULL,
    fecha_hora     TIMESTAMP  NOT NULL,
    diagnostico    TEXT       NOT NULL,
    orientacion    TEXT,
    otros_datos    TEXT,
    observaciones  TEXT,
    CONSTRAINT pk_consulta PRIMARY KEY (id_consulta),
    CONSTRAINT uq_consulta_cita UNIQUE (id_cita),
    CONSTRAINT fk_consulta_cita FOREIGN KEY (id_cita)
        REFERENCES cita (id_cita)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Receta médica emitida en una consulta
CREATE TABLE receta (
    id_receta           INTEGER  GENERATED BY DEFAULT AS IDENTITY,
    id_consulta         INTEGER  NOT NULL,
    fecha               DATE     NOT NULL,
    fecha_proxima_cita  DATE,
    CONSTRAINT pk_receta PRIMARY KEY (id_receta),
    -- La próxima cita debe ser posterior a la fecha de la receta
    CONSTRAINT ck_receta_proxima_cita CHECK (fecha_proxima_cita > fecha),
    CONSTRAINT fk_receta_consulta FOREIGN KEY (id_consulta)
        REFERENCES consulta (id_consulta)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Asociativa receta-medicamento (M:N): prescripción con dosis y duración
CREATE TABLE receta_medicamento (
    id_receta       INTEGER       NOT NULL,
    id_medicamento  INTEGER       NOT NULL,
    dosis           VARCHAR(100)  NOT NULL,
    duracion        VARCHAR(50)   NOT NULL,
    CONSTRAINT pk_receta_medicamento PRIMARY KEY (id_receta, id_medicamento),
    CONSTRAINT fk_receta_medicamento_receta FOREIGN KEY (id_receta)
        REFERENCES receta (id_receta)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_receta_medicamento_medicamento FOREIGN KEY (id_medicamento)
        REFERENCES medicamento (id_medicamento)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Órdenes de laboratorio emitidas en una consulta
CREATE TABLE orden_laboratorio (
    id_orden      INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    id_consulta   INTEGER       NOT NULL,
    examen        VARCHAR(100)  NOT NULL,
    indicaciones  VARCHAR(250),
    CONSTRAINT pk_orden_laboratorio PRIMARY KEY (id_orden),
    CONSTRAINT fk_orden_laboratorio_consulta FOREIGN KEY (id_consulta)
        REFERENCES consulta (id_consulta)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- =====================================================================
-- 5. FICHAS DE TRASLADO, INGRESO Y EGRESO (Emergencias, Cirugía, Hospitalización)
-- =====================================================================

-- Ficha de traslado de un paciente entre unidades (internas o externas)
CREATE TABLE ficha_traslado (
    id_traslado          INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    id_paciente          INTEGER       NOT NULL,
    fecha_hora           TIMESTAMP     NOT NULL,
    edad_anios           SMALLINT      NOT NULL,
    id_medico_indica     INTEGER       NOT NULL,
    id_unidad_origen     INTEGER       NOT NULL,
    id_servicio_origen   SMALLINT      NOT NULL,
    id_unidad_destino    INTEGER       NOT NULL,
    id_servicio_destino  SMALLINT      NOT NULL,
    id_consulta_origen   INTEGER,
    motivo               VARCHAR(250)  NOT NULL,
    consentimiento_de    VARCHAR(9)    NOT NULL,
    id_encargado         INTEGER,
    CONSTRAINT pk_ficha_traslado PRIMARY KEY (id_traslado),
    -- Edad en años dentro de rango válido
    CONSTRAINT ck_ficha_traslado_edad CHECK (edad_anios BETWEEN 0 AND 120),
    -- Unidad de origen y destino deben ser distintas
    CONSTRAINT ck_ficha_traslado_unidades CHECK (id_unidad_origen <> id_unidad_destino),
    -- Consentimiento otorgado por el paciente o por su encargado
    CONSTRAINT ck_ficha_traslado_consent CHECK (consentimiento_de IN ('Paciente', 'Encargado')),
    -- Si consiente el encargado, debe identificarse; si consiente el paciente, no
    CONSTRAINT ck_ficha_traslado_encargado CHECK ((consentimiento_de = 'Encargado') = (id_encargado IS NOT NULL)),
    CONSTRAINT fk_ficha_traslado_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_traslado_medico FOREIGN KEY (id_medico_indica)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_traslado_origen FOREIGN KEY (id_unidad_origen, id_servicio_origen)
        REFERENCES unidad_servicio (id_unidad, id_servicio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_traslado_destino FOREIGN KEY (id_unidad_destino, id_servicio_destino)
        REFERENCES unidad_servicio (id_unidad, id_servicio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_traslado_consulta FOREIGN KEY (id_consulta_origen)
        REFERENCES consulta (id_consulta)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_traslado_encargado FOREIGN KEY (id_paciente, id_encargado)
        REFERENCES paciente_encargado (id_paciente, id_encargado)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Ficha de ingreso a Emergencias, Cirugía u Hospitalización
CREATE TABLE ficha_ingreso (
    id_ingreso              INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    id_paciente             INTEGER       NOT NULL,
    edad_anios              SMALLINT      NOT NULL,
    id_encargado            INTEGER,
    id_unidad               INTEGER       NOT NULL,
    id_servicio             SMALLINT      NOT NULL,
    fecha_hora              TIMESTAMP     NOT NULL,
    id_medico               INTEGER       NOT NULL,
    id_camilla              INTEGER,
    id_quirofano            INTEGER,
    id_traslado             INTEGER,
    motivo_ingreso          VARCHAR(250)  NOT NULL,
    diagnostico_presuntivo  VARCHAR(250)  NOT NULL,
    estado_actual           VARCHAR(250),
    prioridad               SMALLINT,
    CONSTRAINT pk_ficha_ingreso PRIMARY KEY (id_ingreso),
    CONSTRAINT uq_ficha_ingreso_traslado UNIQUE (id_traslado),
    -- Edad en años dentro de rango válido
    CONSTRAINT ck_ficha_ingreso_edad CHECK (edad_anios BETWEEN 0 AND 120),
    -- Se asigna camilla o quirófano, nunca ambos
    CONSTRAINT ck_ficha_ingreso_ubicacion CHECK (id_camilla IS NULL OR id_quirofano IS NULL),
    -- Prioridad de triage: 1 (más urgente) a 5 (menos urgente)
    CONSTRAINT ck_ficha_ingreso_prioridad CHECK (prioridad BETWEEN 1 AND 5),
    CONSTRAINT fk_ficha_ingreso_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_ingreso_encargado FOREIGN KEY (id_paciente, id_encargado)
        REFERENCES paciente_encargado (id_paciente, id_encargado)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_ingreso_unidad_servicio FOREIGN KEY (id_unidad, id_servicio)
        REFERENCES unidad_servicio (id_unidad, id_servicio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_ingreso_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_ingreso_camilla FOREIGN KEY (id_camilla)
        REFERENCES camilla (id_camilla)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_ingreso_quirofano FOREIGN KEY (id_quirofano)
        REFERENCES quirofano (id_quirofano)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_ingreso_traslado FOREIGN KEY (id_traslado)
        REFERENCES ficha_traslado (id_traslado)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Ficha de egreso: cierre de un ingreso (1:1 con ficha_ingreso)
CREATE TABLE ficha_egreso (
    id_egreso                  INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    id_ingreso                 INTEGER       NOT NULL,
    fecha_hora                 TIMESTAMP     NOT NULL,
    edad_anios                 SMALLINT      NOT NULL,
    id_medico                  INTEGER       NOT NULL,
    diagnostico_principal      VARCHAR(250)  NOT NULL,
    motivo_egreso              VARCHAR(250)  NOT NULL,
    codigo_egreso              VARCHAR(8)    NOT NULL,
    sin_consentimiento         BOOLEAN       NOT NULL DEFAULT FALSE,
    motivo_sin_consentimiento  VARCHAR(250),
    dias_hospitalizado         SMALLINT,
    id_traslado                INTEGER,
    id_hospital_referido       SMALLINT,
    CONSTRAINT pk_ficha_egreso PRIMARY KEY (id_egreso),
    CONSTRAINT uq_ficha_egreso_ingreso UNIQUE (id_ingreso),
    CONSTRAINT uq_ficha_egreso_traslado UNIQUE (id_traslado),
    -- Edad en años dentro de rango válido
    CONSTRAINT ck_ficha_egreso_edad CHECK (edad_anios BETWEEN 0 AND 120),
    -- Código de egreso: vivo, muerto, embarazo o parto
    CONSTRAINT ck_ficha_egreso_codigo CHECK (codigo_egreso IN ('Vivo', 'Muerto', 'Embarazo', 'Parto')),
    -- El motivo es obligatorio solo si el egreso fue sin consentimiento médico
    CONSTRAINT ck_ficha_egreso_sin_consent CHECK (sin_consentimiento = (motivo_sin_consentimiento IS NOT NULL)),
    -- Días hospitalizado no negativo
    CONSTRAINT ck_ficha_egreso_dias CHECK (dias_hospitalizado >= 0),
    CONSTRAINT fk_ficha_egreso_ingreso FOREIGN KEY (id_ingreso)
        REFERENCES ficha_ingreso (id_ingreso)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_egreso_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_egreso_traslado FOREIGN KEY (id_traslado)
        REFERENCES ficha_traslado (id_traslado)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_ficha_egreso_hospital FOREIGN KEY (id_hospital_referido)
        REFERENCES hospital (id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Diagnósticos secundarios de un egreso (atributo multivaluado, entidad débil)
CREATE TABLE egreso_diagnostico (
    id_egreso    INTEGER       NOT NULL,
    numero       SMALLINT      NOT NULL,
    descripcion  VARCHAR(250)  NOT NULL,
    CONSTRAINT pk_egreso_diagnostico PRIMARY KEY (id_egreso, numero),
    -- Correlativo positivo
    CONSTRAINT ck_egreso_diagnostico_numero CHECK (numero > 0),
    CONSTRAINT fk_egreso_diagnostico_egreso FOREIGN KEY (id_egreso)
        REFERENCES ficha_egreso (id_egreso)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- =====================================================================
-- 6. CIRUGÍA
-- =====================================================================

-- Historia clínica preoperatoria: interrogatorio del cirujano al paciente
CREATE TABLE historia_clinica (
    id_historia                 INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    id_paciente                 INTEGER       NOT NULL,
    id_medico                   INTEGER       NOT NULL,
    fecha                       DATE          NOT NULL,
    tipo_interrogatorio         VARCHAR(9)    NOT NULL,
    informante                  VARCHAR(120),
    edad_anios                  SMALLINT      NOT NULL,
    religion                    VARCHAR(40),
    ocupacion                   VARCHAR(60),
    lugar_nacimiento            VARCHAR(80),
    lugar_residencia            VARCHAR(80),
    antecedentes_heredofamiliares  TEXT,
    antecedentes_no_patologicos    TEXT,
    antecedentes_patologicos       TEXT,
    padecimiento_actual         TEXT          NOT NULL,
    interrogatorio_sistemas     TEXT,
    sintomas_terapeutica        TEXT,
    estudios_previos            TEXT,
    CONSTRAINT pk_historia_clinica PRIMARY KEY (id_historia),
    -- Interrogatorio directo (paciente) o indirecto (familiar/amigo)
    CONSTRAINT ck_historia_clinica_tipo CHECK (tipo_interrogatorio IN ('Directo', 'Indirecto')),
    -- El informante se registra solo en interrogatorio indirecto
    CONSTRAINT ck_historia_clinica_informante CHECK ((tipo_interrogatorio = 'Indirecto') = (informante IS NOT NULL)),
    -- Edad en años dentro de rango válido
    CONSTRAINT ck_historia_clinica_edad CHECK (edad_anios BETWEEN 0 AND 120),
    CONSTRAINT fk_historia_clinica_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_historia_clinica_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Exploración física de la historia clínica (1:1)
CREATE TABLE exploracion_fisica (
    id_historia              INTEGER       NOT NULL,
    presion_sistolica        SMALLINT      NOT NULL,
    presion_diastolica       SMALLINT      NOT NULL,
    frecuencia_cardiaca      SMALLINT      NOT NULL,
    frecuencia_respiratoria  SMALLINT      NOT NULL,
    temperatura              NUMERIC(4,1)  NOT NULL,
    saturacion_o2            SMALLINT,
    exploracion_general      TEXT          NOT NULL,
    cabeza                   TEXT,
    cuello                   TEXT,
    torax                    TEXT,
    abdomen                  TEXT,
    extremidades             TEXT,
    columna_vertebral        TEXT,
    cavidades                TEXT,
    CONSTRAINT pk_exploracion_fisica PRIMARY KEY (id_historia),
    -- Presión sistólica en mmHg dentro de rango fisiológico
    CONSTRAINT ck_exploracion_fisica_sistolica CHECK (presion_sistolica BETWEEN 40 AND 300),
    -- Presión diastólica en mmHg, menor que la sistólica
    CONSTRAINT ck_exploracion_fisica_diastolica CHECK (presion_diastolica BETWEEN 20 AND 200
                                                        AND presion_diastolica < presion_sistolica),
    -- Frecuencia cardíaca (lpm)
    CONSTRAINT ck_exploracion_fisica_fc CHECK (frecuencia_cardiaca BETWEEN 20 AND 250),
    -- Frecuencia respiratoria (rpm)
    CONSTRAINT ck_exploracion_fisica_fr CHECK (frecuencia_respiratoria BETWEEN 4 AND 80),
    -- Temperatura corporal en °C
    CONSTRAINT ck_exploracion_fisica_temp CHECK (temperatura BETWEEN 30 AND 45),
    -- Saturación de oxígeno en porcentaje
    CONSTRAINT ck_exploracion_fisica_sat CHECK (saturacion_o2 BETWEEN 50 AND 100),
    CONSTRAINT fk_exploracion_fisica_historia FOREIGN KEY (id_historia)
        REFERENCES historia_clinica (id_historia)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Agendamiento quirúrgico: solicitud del cirujano revisada por el comité médico
CREATE TABLE solicitud_cirugia (
    id_solicitud            INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_paciente             INTEGER      NOT NULL,
    edad_anios              SMALLINT     NOT NULL,
    id_historia             INTEGER      NOT NULL,
    id_cirujano             INTEGER      NOT NULL,
    id_unidad               INTEGER      NOT NULL,
    caracter                VARCHAR(10)  NOT NULL,
    tiempo_estimado_min     SMALLINT     NOT NULL,
    tipo_anestesia          VARCHAR(10)  NOT NULL,
    fecha_hora_solicitud    TIMESTAMP    NOT NULL,
    estado                  VARCHAR(9)   NOT NULL DEFAULT 'Pendiente',
    fecha_revision          DATE,
    fecha_hora_programada   TIMESTAMP,
    id_quirofano            INTEGER,
    CONSTRAINT pk_solicitud_cirugia PRIMARY KEY (id_solicitud),
    -- Edad en años dentro de rango válido
    CONSTRAINT ck_solicitud_cirugia_edad CHECK (edad_anios BETWEEN 0 AND 120),
    -- Carácter de la cirugía Urgente / Programado
    CONSTRAINT ck_solicitud_cirugia_caracter CHECK (caracter IN ('Urgente', 'Programado')),
    -- Tiempo estimado entre 1 minuto y 24 horas
    CONSTRAINT ck_solicitud_cirugia_tiempo CHECK (tiempo_estimado_min BETWEEN 1 AND 1440),
    -- Tipo de anestesia válido
    CONSTRAINT ck_solicitud_cirugia_anestesia CHECK (tipo_anestesia IN ('General', 'Regional', 'Local', 'Sedación')),
    -- Estado de la solicitud ante el comité
    CONSTRAINT ck_solicitud_cirugia_estado CHECK (estado IN ('Pendiente', 'Aprobada', 'Rechazada')),
    -- Una solicitud revisada (aprobada/rechazada) debe tener fecha de revisión
    CONSTRAINT ck_solicitud_cirugia_revision CHECK ((estado = 'Pendiente') = (fecha_revision IS NULL)),
    -- Solo una solicitud aprobada tiene fecha/hora y quirófano asignados
    CONSTRAINT ck_solicitud_cirugia_agenda CHECK (
        (estado = 'Aprobada') = (fecha_hora_programada IS NOT NULL AND id_quirofano IS NOT NULL)),
    -- Las cirugías programadas se agendan en horario matutino/vespertino (07:00-18:59)
    CONSTRAINT ck_solicitud_cirugia_horario CHECK (caracter = 'Urgente' OR fecha_hora_programada IS NULL
        OR fecha_hora_programada::TIME BETWEEN TIME '07:00' AND TIME '18:59'),
    CONSTRAINT fk_solicitud_cirugia_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_cirugia_historia FOREIGN KEY (id_historia)
        REFERENCES historia_clinica (id_historia)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_cirugia_cirujano FOREIGN KEY (id_cirujano)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_cirugia_unidad FOREIGN KEY (id_unidad)
        REFERENCES unidad_medica (id_unidad)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_cirugia_quirofano FOREIGN KEY (id_quirofano)
        REFERENCES quirofano (id_quirofano)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Asociativa solicitud-servicio (M:N): procedimientos quirúrgicos a realizar
CREATE TABLE solicitud_procedimiento (
    id_solicitud  INTEGER       NOT NULL,
    id_servicio   SMALLINT      NOT NULL,
    descripcion   VARCHAR(250),
    CONSTRAINT pk_solicitud_procedimiento PRIMARY KEY (id_solicitud, id_servicio),
    CONSTRAINT fk_solicitud_procedimiento_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_cirugia (id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_procedimiento_servicio FOREIGN KEY (id_servicio)
        REFERENCES servicio (id_servicio)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Cirugías rechazadas por el comité, con las razones (1:1 con solicitud)
CREATE TABLE cirugia_rechazada (
    id_solicitud   INTEGER  NOT NULL,
    fecha_rechazo  DATE     NOT NULL,
    razones        TEXT     NOT NULL,
    CONSTRAINT pk_cirugia_rechazada PRIMARY KEY (id_solicitud),
    CONSTRAINT fk_cirugia_rechazada_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_cirugia (id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Catálogo de insumos médicos y quirúrgicos
CREATE TABLE insumo (
    id_insumo        INTEGER        GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(80)    NOT NULL,
    descripcion      VARCHAR(250),
    material         VARCHAR(60),
    tipo             VARCHAR(10)    NOT NULL,
    precio_unitario  NUMERIC(10,2)  NOT NULL,
    CONSTRAINT pk_insumo PRIMARY KEY (id_insumo),
    CONSTRAINT uq_insumo_nombre UNIQUE (nombre),
    -- Tipo de insumo: médico, quirúrgico u otro
    CONSTRAINT ck_insumo_tipo CHECK (tipo IN ('Médico', 'Quirúrgico', 'Otro')),
    -- Precio unitario no negativo
    CONSTRAINT ck_insumo_precio CHECK (precio_unitario >= 0)
);

-- Catálogo de instrumental
CREATE TABLE instrumento (
    id_instrumento  INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(80)   NOT NULL,
    descripcion     VARCHAR(250),
    tipo            VARCHAR(10)   NOT NULL,
    funcion         VARCHAR(11)   NOT NULL,
    CONSTRAINT pk_instrumento PRIMARY KEY (id_instrumento),
    CONSTRAINT uq_instrumento_nombre UNIQUE (nombre),
    -- Tipo de instrumento: médico, quirúrgico u otro
    CONSTRAINT ck_instrumento_tipo CHECK (tipo IN ('Médico', 'Quirúrgico', 'Otro')),
    -- Función del instrumento
    CONSTRAINT ck_instrumento_funcion CHECK (funcion IN
        ('Corte', 'Contenido', 'Hemostática', 'Retractor', 'Accesorio', 'Implante', 'Otro'))
);

-- Catálogo de equipos
CREATE TABLE equipo (
    id_equipo    INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    nombre       VARCHAR(80)   NOT NULL,
    descripcion  VARCHAR(250),
    tipo         VARCHAR(10)   NOT NULL,
    funcion      VARCHAR(14)   NOT NULL,
    CONSTRAINT pk_equipo PRIMARY KEY (id_equipo),
    CONSTRAINT uq_equipo_nombre UNIQUE (nombre),
    -- Tipo de equipo: médico, quirúrgico u otro
    CONSTRAINT ck_equipo_tipo CHECK (tipo IN ('Médico', 'Quirúrgico', 'Otro')),
    -- Función del equipo
    CONSTRAINT ck_equipo_funcion CHECK (funcion IN
        ('Exploración', 'Diagnóstico', 'Tratamiento', 'Rehabilitación', 'Otro'))
);

-- Asociativa solicitud-insumo (M:N): insumos requeridos para la cirugía
CREATE TABLE solicitud_insumo (
    id_solicitud  INTEGER   NOT NULL,
    id_insumo     INTEGER   NOT NULL,
    cantidad      SMALLINT  NOT NULL,
    CONSTRAINT pk_solicitud_insumo PRIMARY KEY (id_solicitud, id_insumo),
    -- Cantidad requerida positiva
    CONSTRAINT ck_solicitud_insumo_cantidad CHECK (cantidad > 0),
    CONSTRAINT fk_solicitud_insumo_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_cirugia (id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_insumo_insumo FOREIGN KEY (id_insumo)
        REFERENCES insumo (id_insumo)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Asociativa solicitud-instrumento (M:N): instrumental requerido
CREATE TABLE solicitud_instrumento (
    id_solicitud    INTEGER   NOT NULL,
    id_instrumento  INTEGER   NOT NULL,
    cantidad        SMALLINT  NOT NULL,
    CONSTRAINT pk_solicitud_instrumento PRIMARY KEY (id_solicitud, id_instrumento),
    -- Cantidad requerida positiva
    CONSTRAINT ck_solicitud_instrumento_cantidad CHECK (cantidad > 0),
    CONSTRAINT fk_solicitud_instrumento_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_cirugia (id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_instrumento_instrumento FOREIGN KEY (id_instrumento)
        REFERENCES instrumento (id_instrumento)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Asociativa solicitud-equipo (M:N): equipos requeridos
CREATE TABLE solicitud_equipo (
    id_solicitud  INTEGER   NOT NULL,
    id_equipo     INTEGER   NOT NULL,
    cantidad      SMALLINT  NOT NULL,
    CONSTRAINT pk_solicitud_equipo PRIMARY KEY (id_solicitud, id_equipo),
    -- Cantidad requerida positiva
    CONSTRAINT ck_solicitud_equipo_cantidad CHECK (cantidad > 0),
    CONSTRAINT fk_solicitud_equipo_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_cirugia (id_solicitud)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_solicitud_equipo_equipo FOREIGN KEY (id_equipo)
        REFERENCES equipo (id_equipo)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Chequeo de consentimiento informado de una solicitud aprobada
CREATE TABLE consentimiento_informado (
    id_consentimiento     INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud          INTEGER       NOT NULL,
    nombre_procedimiento  VARCHAR(150)  NOT NULL,
    objetivo              TEXT          NOT NULL,
    caracteristicas       TEXT          NOT NULL,
    riesgos               TEXT          NOT NULL,
    id_medico             INTEGER       NOT NULL,
    firma_medico          BOOLEAN       NOT NULL,
    nombre_firmante       VARCHAR(160)  NOT NULL,
    tipo_firmante         VARCHAR(20)   NOT NULL,
    firma_firmante        BOOLEAN       NOT NULL,
    fecha_obtencion       DATE          NOT NULL,
    CONSTRAINT pk_consentimiento_informado PRIMARY KEY (id_consentimiento),
    -- Quién firma: paciente, familiar, tutor o representante legal
    CONSTRAINT ck_consentimiento_tipo_firmante CHECK (tipo_firmante IN
        ('Paciente', 'Familiar', 'Tutor', 'Representante legal')),
    CONSTRAINT fk_consentimiento_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_cirugia (id_solicitud)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_consentimiento_medico FOREIGN KEY (id_medico)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Chequeo preanestésico de una solicitud aprobada (1:1)
CREATE TABLE chequeo_preanestesico (
    id_chequeo             INTEGER   GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud           INTEGER   NOT NULL,
    clasificacion_asa      SMALLINT  NOT NULL,
    id_medico_clasifica    INTEGER   NOT NULL,
    firma_medico_clasifica BOOLEAN   NOT NULL,
    plan_anestesia         TEXT      NOT NULL,
    id_anestesista         INTEGER   NOT NULL,
    fecha                  DATE      NOT NULL,
    CONSTRAINT pk_chequeo_preanestesico PRIMARY KEY (id_chequeo),
    CONSTRAINT uq_chequeo_preanestesico_solicitud UNIQUE (id_solicitud),
    -- Clasificación ASA de riesgo anestésico: I a VI
    CONSTRAINT ck_chequeo_preanestesico_asa CHECK (clasificacion_asa BETWEEN 1 AND 6),
    CONSTRAINT fk_chequeo_preanestesico_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_cirugia (id_solicitud)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_chequeo_preanestesico_clasifica FOREIGN KEY (id_medico_clasifica)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_chequeo_preanestesico_anestesista FOREIGN KEY (id_anestesista)
        REFERENCES medico (id_medico)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Cirugía aprobada y su ejecución (1:1 con solicitud aprobada)
CREATE TABLE cirugia (
    id_cirugia              INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud            INTEGER      NOT NULL,
    id_quirofano            INTEGER      NOT NULL,
    id_ingreso              INTEGER,
    id_enfermero_encargado  INTEGER      NOT NULL,
    estado                  VARCHAR(10)  NOT NULL DEFAULT 'Programada',
    fecha_hora_inicio       TIMESTAMP,
    fecha_hora_fin          TIMESTAMP,
    condicion_evolucion     VARCHAR(22),
    CONSTRAINT pk_cirugia PRIMARY KEY (id_cirugia),
    CONSTRAINT uq_cirugia_solicitud UNIQUE (id_solicitud),
    CONSTRAINT uq_cirugia_ingreso UNIQUE (id_ingreso),
    -- Estado de la cirugía
    CONSTRAINT ck_cirugia_estado CHECK (estado IN ('Programada', 'En curso', 'Finalizada', 'Suspendida')),
    -- La hora de fin debe ser posterior a la de inicio
    CONSTRAINT ck_cirugia_fechas CHECK (fecha_hora_fin > fecha_hora_inicio),
    -- Una cirugía finalizada debe tener hora de inicio y de fin
    CONSTRAINT ck_cirugia_finalizada CHECK (estado <> 'Finalizada'
        OR (fecha_hora_inicio IS NOT NULL AND fecha_hora_fin IS NOT NULL)),
    -- Condición de evolución durante la cirugía
    CONSTRAINT ck_cirugia_condicion CHECK (condicion_evolucion IN
        ('Sin complicaciones', 'Complicaciones', 'Complicaciones graves')),
    CONSTRAINT fk_cirugia_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_cirugia (id_solicitud)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cirugia_quirofano FOREIGN KEY (id_quirofano)
        REFERENCES quirofano (id_quirofano)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cirugia_ingreso FOREIGN KEY (id_ingreso)
        REFERENCES ficha_ingreso (id_ingreso)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cirugia_enfermero FOREIGN KEY (id_enfermero_encargado)
        REFERENCES enfermero (id_enfermero)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Asociativa cirugía-persona (M:N): equipo de salud que participa en la cirugía
CREATE TABLE cirugia_personal (
    id_cirugia  INTEGER      NOT NULL,
    id_persona  INTEGER      NOT NULL,
    rol         VARCHAR(30)  NOT NULL,
    CONSTRAINT pk_cirugia_personal PRIMARY KEY (id_cirugia, id_persona),
    -- Rol dentro del equipo quirúrgico
    CONSTRAINT ck_cirugia_personal_rol CHECK (rol IN
        ('Cirujano principal', 'Cirujano asistente', 'Anestesiólogo', 'Enfermero instrumentista',
         'Enfermero circulante', 'Practicante de medicina', 'Practicante de enfermería')),
    CONSTRAINT fk_cirugia_personal_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cirugia_personal_persona FOREIGN KEY (id_persona)
        REFERENCES persona (id_persona)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Catálogo de aspectos a verificar en cada etapa del proceso quirúrgico
CREATE TABLE item_verificacion (
    id_item         SMALLINT      GENERATED BY DEFAULT AS IDENTITY,
    fase            VARCHAR(15)   NOT NULL,
    etapa           VARCHAR(40)   NOT NULL,
    descripcion     VARCHAR(200)  NOT NULL,
    tipo_resultado  VARCHAR(11)   NOT NULL,
    CONSTRAINT pk_item_verificacion PRIMARY KEY (id_item),
    CONSTRAINT uq_item_verificacion_etapa_desc UNIQUE (etapa, descripcion),
    CONSTRAINT uq_item_verificacion_item_tipo UNIQUE (id_item, tipo_resultado),
    -- Fase del proceso quirúrgico
    CONSTRAINT ck_item_verificacion_fase CHECK (fase IN ('Preoperatorio', 'Intraoperatorio', 'Postoperatorio')),
    -- Etapa del proceso quirúrgico
    CONSTRAINT ck_item_verificacion_etapa CHECK (etapa IN
        ('Planificación', 'Entrada', 'Chequeo en quirófano', 'Pausa quirúrgica',
         'Cuidados intraoperatorios', 'Salida quirúrgica',
         'Ingreso a sala de recuperación', 'Traslado seguro')),
    -- Forma de evaluar el aspecto: éxito/fallo o valoración de aceptabilidad
    CONSTRAINT ck_item_verificacion_tipo CHECK (tipo_resultado IN ('Éxito/Fallo', 'Valoración'))
);

-- Registro del resultado de cada aspecto verificado en una cirugía
CREATE TABLE registro_verificacion (
    id_cirugia      INTEGER       NOT NULL,
    id_item         SMALLINT      NOT NULL,
    tipo_resultado  VARCHAR(11)   NOT NULL,
    resultado       VARCHAR(22)   NOT NULL,
    fecha_hora      TIMESTAMP     NOT NULL,
    descripcion     VARCHAR(250),
    id_enfermero    INTEGER       NOT NULL,
    CONSTRAINT pk_registro_verificacion PRIMARY KEY (id_cirugia, id_item),
    -- El resultado debe corresponder al tipo de evaluación del aspecto
    CONSTRAINT ck_registro_verificacion_resultado CHECK (
        (tipo_resultado = 'Éxito/Fallo' AND resultado IN ('Éxito', 'Fallo'))
        OR (tipo_resultado = 'Valoración' AND resultado IN ('Aceptable', 'Medianamente aceptable', 'No aceptable'))),
    CONSTRAINT fk_registro_verificacion_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_registro_verificacion_item FOREIGN KEY (id_item, tipo_resultado)
        REFERENCES item_verificacion (id_item, tipo_resultado)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_registro_verificacion_enfermero FOREIGN KEY (id_enfermero)
        REFERENCES enfermero (id_enfermero)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Documentación de cada fase de la cirugía enviada a secretaría
CREATE TABLE cirugia_documento (
    id_cirugia    INTEGER       NOT NULL,
    fase          VARCHAR(15)   NOT NULL,
    id_enfermero  INTEGER       NOT NULL,
    fecha_envio   DATE          NOT NULL,
    observaciones VARCHAR(250),
    CONSTRAINT pk_cirugia_documento PRIMARY KEY (id_cirugia, fase),
    -- Fase documentada
    CONSTRAINT ck_cirugia_documento_fase CHECK (fase IN ('Preoperatorio', 'Intraoperatorio', 'Postoperatorio')),
    CONSTRAINT fk_cirugia_documento_cirugia FOREIGN KEY (id_cirugia)
        REFERENCES cirugia (id_cirugia)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_cirugia_documento_enfermero FOREIGN KEY (id_enfermero)
        REFERENCES enfermero (id_enfermero)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Insumos consumidos durante un ingreso (cirugía u hospitalización), base del cobro
CREATE TABLE consumo_insumo (
    id_consumo       INTEGER        GENERATED BY DEFAULT AS IDENTITY,
    id_ingreso       INTEGER        NOT NULL,
    id_insumo        INTEGER        NOT NULL,
    fecha_hora       TIMESTAMP      NOT NULL,
    cantidad         NUMERIC(8,2)   NOT NULL,
    precio_unitario  NUMERIC(10,2)  NOT NULL,
    subtotal         NUMERIC(12,2)  GENERATED ALWAYS AS (ROUND(cantidad * precio_unitario, 2)) STORED,
    CONSTRAINT pk_consumo_insumo PRIMARY KEY (id_consumo),
    -- Cantidad consumida positiva
    CONSTRAINT ck_consumo_insumo_cantidad CHECK (cantidad > 0),
    -- Precio unitario no negativo
    CONSTRAINT ck_consumo_insumo_precio CHECK (precio_unitario >= 0),
    CONSTRAINT fk_consumo_insumo_ingreso FOREIGN KEY (id_ingreso)
        REFERENCES ficha_ingreso (id_ingreso)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_consumo_insumo_insumo FOREIGN KEY (id_insumo)
        REFERENCES insumo (id_insumo)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- =====================================================================
-- 7. FACTURACIÓN Y CALIFICACIONES
-- =====================================================================

-- Factura emitida al cancelar el servicio (de una cita o de un ingreso)
CREATE TABLE factura (
    id_factura     INTEGER        GENERATED BY DEFAULT AS IDENTITY,
    numero         VARCHAR(20)    NOT NULL,
    id_hospital    SMALLINT       NOT NULL,
    id_paciente    INTEGER        NOT NULL,
    nit            VARCHAR(12)    NOT NULL DEFAULT 'CF',
    fecha_emision  TIMESTAMP      NOT NULL,
    descripcion    VARCHAR(250)   NOT NULL,
    id_cita        INTEGER,
    id_ingreso     INTEGER,
    numero_cuotas  SMALLINT       NOT NULL DEFAULT 1,
    total          NUMERIC(12,2)  NOT NULL,
    CONSTRAINT pk_factura PRIMARY KEY (id_factura),
    CONSTRAINT uq_factura_numero UNIQUE (numero),
    CONSTRAINT uq_factura_cita UNIQUE (id_cita),
    CONSTRAINT uq_factura_ingreso UNIQUE (id_ingreso),
    -- NIT numérico (con dígito verificador opcional K) o Consumidor Final
    CONSTRAINT ck_factura_nit CHECK (nit = 'CF' OR nit ~ '^[0-9]{1,11}[0-9K]$'),
    -- La factura corresponde a una cita o a un ingreso, exactamente uno
    CONSTRAINT ck_factura_origen CHECK (num_nonnulls(id_cita, id_ingreso) = 1),
    -- Pago en 1 a 12 cuotas mensuales
    CONSTRAINT ck_factura_cuotas CHECK (numero_cuotas BETWEEN 1 AND 12),
    -- La consulta externa se cancela en su totalidad (una sola cuota)
    CONSTRAINT ck_factura_cuotas_cita CHECK (id_cita IS NULL OR numero_cuotas = 1),
    -- Total no negativo
    CONSTRAINT ck_factura_total CHECK (total >= 0),
    CONSTRAINT fk_factura_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_factura_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_factura_cita FOREIGN KEY (id_cita)
        REFERENCES cita (id_cita)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_factura_ingreso FOREIGN KEY (id_ingreso)
        REFERENCES ficha_ingreso (id_ingreso)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Líneas de detalle de la factura (entidad débil)
CREATE TABLE detalle_factura (
    id_factura       INTEGER        NOT NULL,
    linea            SMALLINT       NOT NULL,
    concepto         VARCHAR(150)   NOT NULL,
    cantidad         NUMERIC(8,2)   NOT NULL,
    precio_unitario  NUMERIC(10,2)  NOT NULL,
    subtotal         NUMERIC(12,2)  GENERATED ALWAYS AS (ROUND(cantidad * precio_unitario, 2)) STORED,
    CONSTRAINT pk_detalle_factura PRIMARY KEY (id_factura, linea),
    -- Número de línea positivo
    CONSTRAINT ck_detalle_factura_linea CHECK (linea > 0),
    -- Cantidad positiva
    CONSTRAINT ck_detalle_factura_cantidad CHECK (cantidad > 0),
    -- Precio unitario no negativo
    CONSTRAINT ck_detalle_factura_precio CHECK (precio_unitario >= 0),
    CONSTRAINT fk_detalle_factura_factura FOREIGN KEY (id_factura)
        REFERENCES factura (id_factura)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Cuotas mensuales de pago de una factura (entidad débil)
CREATE TABLE cuota_pago (
    id_factura         INTEGER        NOT NULL,
    numero_cuota       SMALLINT       NOT NULL,
    monto              NUMERIC(12,2)  NOT NULL,
    fecha_vencimiento  DATE           NOT NULL,
    fecha_pago         DATE,
    lugar_pago         VARCHAR(30)    NOT NULL,
    CONSTRAINT pk_cuota_pago PRIMARY KEY (id_factura, numero_cuota),
    -- Número de cuota entre 1 y 12
    CONSTRAINT ck_cuota_pago_numero CHECK (numero_cuota BETWEEN 1 AND 12),
    -- Monto de la cuota positivo
    CONSTRAINT ck_cuota_pago_monto CHECK (monto > 0),
    -- Recepción donde se realiza el pago según la unidad
    CONSTRAINT ck_cuota_pago_lugar CHECK (lugar_pago IN
        ('Recepción del médico', 'Recepción de hospitalización', 'Recepción de cirugía')),
    CONSTRAINT fk_cuota_pago_factura FOREIGN KEY (id_factura)
        REFERENCES factura (id_factura)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Calificaciones de calidad del servicio: hospital, médico, enfermero o encargado de unidad
CREATE TABLE calificacion (
    id_calificacion        INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    id_hospital            SMALLINT     NOT NULL,
    tipo_calificado        VARCHAR(9)   NOT NULL,
    id_persona_calificada  INTEGER,
    id_paciente            INTEGER,
    puntuacion             SMALLINT     NOT NULL,
    comentario             VARCHAR(250),
    fecha                  DATE         NOT NULL,
    CONSTRAINT pk_calificacion PRIMARY KEY (id_calificacion),
    -- Objeto calificado
    CONSTRAINT ck_calificacion_tipo CHECK (tipo_calificado IN ('Hospital', 'Médico', 'Enfermero', 'Encargado')),
    -- Si se califica al hospital no hay persona calificada; en otro caso es obligatoria
    CONSTRAINT ck_calificacion_persona CHECK ((tipo_calificado = 'Hospital') = (id_persona_calificada IS NULL)),
    -- Puntuación de 1 a 5
    CONSTRAINT ck_calificacion_puntuacion CHECK (puntuacion BETWEEN 1 AND 5),
    CONSTRAINT fk_calificacion_hospital FOREIGN KEY (id_hospital)
        REFERENCES hospital (id_hospital)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_calificacion_persona FOREIGN KEY (id_persona_calificada)
        REFERENCES persona (id_persona)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_calificacion_paciente FOREIGN KEY (id_paciente)
        REFERENCES paciente (id_paciente)
        ON DELETE SET NULL ON UPDATE CASCADE
);

-- =====================================================================
-- 8. ÍNDICES SOBRE LLAVES FORÁNEAS DE CONSULTA FRECUENTE
-- =====================================================================
CREATE INDEX ix_cita_paciente        ON cita (id_paciente);
CREATE INDEX ix_cita_medico_fecha    ON cita (id_medico, fecha_hora);
CREATE INDEX ix_ficha_ingreso_pac    ON ficha_ingreso (id_paciente);
CREATE INDEX ix_ficha_ingreso_unidad ON ficha_ingreso (id_unidad, fecha_hora);
CREATE INDEX ix_ficha_traslado_pac   ON ficha_traslado (id_paciente);
CREATE INDEX ix_solicitud_paciente   ON solicitud_cirugia (id_paciente);
CREATE INDEX ix_factura_paciente     ON factura (id_paciente);
CREATE INDEX ix_calificacion_hosp    ON calificacion (id_hospital);
